apiVersion: v1
kind: Secret
metadata:
  name: cluster-manager-secret
  namespace: mapreduce
type: Opaque
stringData:
  CLUSTER_MANAGER_INTERNAL_TOKEN: 457bcc8d05e54d1d9f628ce9308e3be4b33cf045b4e948c1aec9793242b51b30
